### ISSUE TITLE
PyTorch version dependancy already exists in the 'environment.yml'

### ISSUE THREAD

**Issue by ChristosPeridis** [tmdt-buw/karolos#6]
Hello dear Christian and dear Thunfisch,

I have also noticed that inside the 'environement.yml' file you have as a dipendancy pytorch=1.11.0. However in your instructions in your main github page you propose to install PyToroch with the following command:

conda install pytorch cudatoolkit=11.1 -c pytorch -c conda-forge

The above command results in the system installing PyTorch version 1.8.1 instead of 11.11.0

Which version is the correct one for running the Karolos code with no issue?

Thank you very much in advance for your valuable help!!!

Kind regards,

Christos Peridis

**Comment by chrisbitter** [comment]
Hey Christos,

I'm currently on my phone. Will get a chance beginning next week to look at
the version I'm running.

However I have been running different pytorch v1 versions without issues in
the past. The reason we recommend the separate installation of pytorch is
that we ran into issues with different cuda versions (and thus different
pytorch versions) on different systems. I'll remove pytorch from the .yml
so that pytorch doesn't get installed twice.

I'll test if everything works with the latest pytorch version 1.13 and if
it does we should update the recommendation to the newest version. Same
thing goes for all the other libraries in the .yml.

Thanks for raising this issue.

Cheers, Christian

**Comment by chrisbitter** [comment]
I just updated the environment.yml and tested everything with a new environment. We are now using the latest pytoch v1 version. Also updated the Readme.

Closing this issue for now. If there are any more issues with getting up and running feel free open a new issue.
